{
 "title": "StrataGo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Raft Consensus State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "stratago_raft_state", "legendFormat": "Node {{node_id}}" }
   ]
  },
  {
   "title": "SSTable Count (Disk Fragmentation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "stratago_sstable_count", "legendFormat": "Node {{node}}" }
   ]
  },
  {
   "title": "Active Memtable Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stratago_memtable_size_bytes", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "P99 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(stratago_grpc_request_duration_seconds_bucket[1m])) by (le, method, consistency))",
     "legendFormat": "{{method}} [{{consistency}}]"
    }
   ]
  },
  {
   "title": "Cluster Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(stratago_requests_total[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}